version: '3.8'

services:
  # --- Database ---
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tesla
      - POSTGRES_PASSWORD=teslapass
      - POSTGRES_DB=tesladb

  # --- Nginx Gateway ---
  gateway:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-gateway/conf.d:/etc/nginx/conf.d:z
    depends_on:
      - backend
      - shop
      - admin

  # --- Backend ---
  backend:
    build:
      context: ./tesla-parts-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://tesla:teslapass@db:5432/tesladb
      - FRONTEND_URL=http://teslapartscenter.com.ua,http://admin.teslapartscenter.com.ua
      - ADMIN_SECRET=${ADMIN_SECRET}
    depends_on:
      - db
      
  # --- Shop Frontend ---
  shop:
    build:
      context: ./tesla-parts-shop
      args:
        # Вказуємо публічну адресу API
        VITE_API_URL: http://api.teslapartscenter.com.ua
    restart: always

  # --- Admin Frontend ---
  admin:
    build:
      context: ./tesla-parts-admin
      args:
        # Вказуємо публічну адресу API
        VITE_API_URL: http://api.teslapartscenter.com.ua
    restart: always

volumes:
  postgres_data: